In [1]:
import numpy as np

In [2]:
arr1 = np.array([2,3,4,6,7]) # 1d array 
arr1

array([2, 3, 4, 6, 7])

**Properties**

In [3]:
print(type(arr1))
print(arr1.dtype)
print(arr1.size)
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)



<class 'numpy.ndarray'>
int32
5
(5,)
1
5


In [4]:
arr = np.array([[3,4,1,5,2,],[3,1,5,6,3]]) #2d array
print(arr)


[[3 4 1 5 2]
 [3 1 5 6 3]]


In [5]:
print(type(arr))
print(arr.dtype) # default int32
print(arr.itemsize)  
print(arr.shape)
print(arr.ndim)
print(arr.size)


<class 'numpy.ndarray'>
int32
4
(2, 5)
2
10


In [6]:
arr = np.array([[3,4,1,5,2,],[3,1,5,6,3]],dtype=np.float64)
arr

array([[3., 4., 1., 5., 2.],
       [3., 1., 5., 6., 3.]])

In [4]:
arr = np.linspace(1,5,5)
arr.dtype

dtype('float64')

**Initilize Array**

In [8]:
print(np.arange(1,5)) # Create array 1 to 4 dtype = int32
print(np.zeros((4,6))) # Create zeros array
print(np.empty((4,6)))
print(np.ones((4,6)))
print(np.linspace(1,5,5)) # Linerally spaced (start, end , genrate 5 no betw s and e )

[1 2 3 4]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[1. 2. 3. 4. 5.]


In [7]:
arr.reshape(5,2) # just multiplication should equal

array([[3., 4.],
       [1., 5.],
       [2., 3.],
       [1., 5.],
       [6., 3.]])

In [10]:
arr

array([1., 2., 3., 4., 5.])

In [11]:
arr.ravel() #will make 1d array

array([1., 2., 3., 4., 5.])

In [12]:
arr

array([1., 2., 3., 4., 5.])

In [13]:
arr.min()

1.0

In [14]:
arr.max()

5.0

In [15]:
arr.sum()

15.0

In [16]:
arr.sum(axis=0) # axis 0 => coloum

15.0

In [20]:
#arr.sum(axis=1) # axis 1 => rows

In [21]:
np.sqrt(arr) 

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [22]:
np.std(arr) # starndard deviation

1.4142135623730951

In [23]:
a1 = np.array([[[5,6],
[7,8]]])
a2 = np.array([[6,8],[10,12]])

In [24]:
a1 + a2

array([[[11, 14],
        [17, 20]]])

In [25]:
a1/a2

array([[[0.83333333, 0.75      ],
        [0.7       , 0.66666667]]])